### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by jhxu003** [yangnianzu0515/MoleRec#2]
Hello! Your work is truly exceptional!
Have you ever experimented with the MIMIC-IV dataset, or have you considered combining both MIMIC-III and MIMIC-IV? 
I'm curious if utilizing the larger dataset would lead to performance improvements.

**Comment by yangnianzu0515** [comment]
Thank you for your acknowledgment!

We haven't conducted experiments on the MIMIC-IV dataset yet. We followed the baseline of GAMENet and SafeDrug, both of which only experimented on MIMIC-III, so we also confined our experiments to MIMIC-III.

Regarding the MIMIC-IV dataset you mentioned, I've recently been considering continuing the task of combinatorial drug recommendation. If I come up with new ideas, I will incorporate this dataset in our subsequent work.

Your idea of combining both MIMIC-III and MIMIC-IV is excellent. To our knowledge, these two EHR datasets have overlapping time spans, which might result in overlapping data samples. If you consider merging them, you might need to deduplicate the records. Of course, you can also treat them as two separate datasets and validate the model performance individually on each.

**Comment by jhxu003** [comment]
Thank you for your reply!
I'm glad I was able to resolve an issue that had been bothering me for a long time. 
Maybe I'll have the opportunity to give it a try in the future.

**Comment by yangnianzu0515** [comment]
Wishing you success!

If you have any further questions, feel free to contact me. I will reply as soon as I can when I'm available.
